# Generated by Django 4.0.1 on 2022-02-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytrack', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyRegister2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('track_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mytracks')),
            ],
        ),
    ]
