# Generated by Django 4.0.1 on 2022-02-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytracks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
